### ISSUE TITLE
Purchase not working in iOS 16

### ISSUE THREAD

**Issue by neowinston** [tikhop/Mercato#7]
When I try to make a purchase using command below nothing happens. The purchase sheet doesn't show up in iOS 16:

```
try await Mercato.purchase(product: product, quantity: 1, finishAutomatically: false, appAccountToken: nil, simulatesAskToBuyInSandbox: false)
```

Is anyone else having the same problem? Thanks for your help!

**Comment by sabiland** [comment]
And no errors, nothing? I don't have any problems for now.
Try to test it locally with [StoreKit configuration file](https://developer.apple.com/documentation/xcode/setting-up-storekit-testing-in-xcode).

**Comment by neowinston** [comment]
I'm testing on the device. I'll try with a StoreKit configuration file.

**Comment by tikhop** [comment]
@neowinston How is it going? Do you still have any issues with Mercato?

**Comment by neowinston** [comment]
Yes, I'm still having problems.  The purchase sheet doesn't show up in iOS 16.

**Comment by tikhop** [comment]
@neowinston I think, I was able to reproduce it when I tried to subscribe to auto-renewable subscription. I was getting success message right away without showing the purchase sheet from StoreKit. For me the issue was in the product item itself, two other subscriptions was working well and after re-creating a product on apple connect everything works well again. 

Could you please, if you have a chance, verify what `Mercato.purchase` returns for you in this case.

```
let purchase = try await Mercato.purchase(product: product, quantity: 1, finishAutomatically: false, appAccountToken: nil, simulatesAskToBuyInSandbox: false)
print(purchase)
```

Thank you!

**Comment by tikhop** [comment]
Here is more info: https://developer.apple.com/forums/thread/723126
